spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jwt:
    secret: Ro20tCmKlUgOF01uACzuCf/Vi3RVo+ulr2owb60AB5K+Sfxd/ACrg7hlFzqZaaNN
    expiration: 86400000
    header: Authorization
    prefix: Bearer


  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
